Repository trustsoothe/vault, pull requests merged in 2025-06, with the labels that each got.

#138 Some fixes and enhacements
  .changeset/few-garlics-wave.md
  apps/nodejs/extension/src/redux/slices/app/index.ts
  apps/nodejs/extension/src/ui/Header/Header.tsx
  apps/nodejs/extension/src/ui/Request/Handler.tsx
  apps/nodejs/extension/src/ui/Request/PersonalSign.tsx
  apps/nodejs/extension/src/ui/Request/RequestInfo.tsx
Labels: bug, enhancement

#145 Display app version and handle browser available updates
  .changeset/beige-pillows-applaud.md
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  apps/nodejs/extension/build/webpack/common.js
  apps/nodejs/extension/src/controllers/background.ts
  apps/nodejs/extension/src/redux/selectors/app.ts
  apps/nodejs/extension/src/redux/slices/app/index.ts
  apps/nodejs/extension/src/ui/Home/Footer.tsx
  apps/nodejs/extension/src/ui/Home/Home.tsx
  apps/nodejs/extension/src/ui/index.tsx
  apps/nodejs/extension/src/utils/ui.tsx
Labels: enhancement

#147 Add Cosmos transaction support in vault import and improve snackbar UI handling
  .changeset/young-planes-stare.md
  apps/nodejs/extension/src/controllers/datasource/Transaction.ts
  apps/nodejs/extension/src/redux/slices/vault/backup.ts
  apps/nodejs/extension/src/utils/ui.tsx
Labels: bug

#153 Add enhanced error handling for failed transactions and UI improvements.
  .changeset/fresh-toys-occur.md
  apps/nodejs/extension/src/controllers/communication/Internal.ts
  apps/nodejs/extension/src/controllers/datasource/Transaction.ts
  apps/nodejs/extension/src/redux/slices/app/index.ts
  apps/nodejs/extension/src/redux/slices/vault/account.ts
  apps/nodejs/extension/src/types/communications/transfer.ts
  apps/nodejs/extension/src/ui/Activity/Activity.tsx
  apps/nodejs/extension/src/ui/Activity/TransactionDetailModal.tsx
  apps/nodejs/extension/src/ui/PoktTransaction/MemoInput.tsx
  apps/nodejs/extension/src/ui/Transaction/BaseTransaction.tsx
  apps/nodejs/extension/src/ui/Transaction/RecipientAutocomplete.tsx
  apps/nodejs/extension/src/ui/Transaction/Submitted.tsx
  apps/nodejs/extension/src/ui/Transaction/TransactionHash.tsx
  apps/nodejs/extension/src/ui/UnlockVault/UnlockVault.tsx
  apps/nodejs/extension/src/ui/components/FailedActionBanner.tsx
  apps/nodejs/extension/src/utils/proxy.ts
  packages/nodejs/vault/src/lib/core/common/protocols/Cosmos/CosmosProtocolService.ts
  packages/nodejs/vault/src/lib/errors/index.ts
Labels: enhancement

#157 Fixes/migrate and more import
  .changeset/dry-snakes-brush.md
  .changeset/smooth-donkeys-drive.md
  apps/nodejs/extension/src/ui/ImportAccount/ImportForm.tsx
  apps/nodejs/extension/src/ui/Migration/MigrateAccount/MigrateAccountDialog.tsx
  apps/nodejs/extension/src/ui/Transaction/RecipientAutocomplete.tsx
  packages/nodejs/vault/src/lib/core/common/protocols/Cosmos/CosmosProtocolService.ts
Labels: bug
